name: note_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # database
  sqflite: ^2.3.0
  # time format
  intl: ^0.18.1
  # grid view
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  # Plugin Flutter untuk menemukan lokasi yang umum digunakan di sistem file.
  path_provider: ^2.1.1
  sqflite_common_ffi: ^2.3.0+2
  anim_search_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
